# FYI, you can validate this file here: https://config.travis-ci.com/explore
os:
  - osx
  - linux
  - windows
jobs:
  allow_failures:
    - os: osx
    - os: windows
language: generic
dist: bionic
addons:
  apt:
    update: true
env:
  - DISPLAY=:99.0
services:
  - xvfb
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install python3; sudo apt-get -y install python3-setuptools; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python --version 3.6.8; PATH=/c/Python36:/c/Python36/Scripts:$PATH; ln -s /c/Python36/python /usr/bin/python3; ln -s /c/Python36/Scripts/pip /usr/bin/pip3; fi
  - export BOTO_CONFIG=/dev/null
install:
  - python3 build.py
script:
  - python3 test.py
